# -*- coding: utf-8 -*-
"""mini-blog API 压测脚本（Locust）。

用法（框架外额外依赖：pip install locust）：
    locust -f performance/locustfile.py --headless -u 10 -r 2 -t 60s --host http://127.0.0.1:8520

行为模型：虚拟用户启动即注册 + 登录获取 token；
以浏览（文章列表 / 标签）为主，低频发文章，贴近真实读多写少的博客场景。
"""

import random

from locust import HttpUser, between, task


class BlogUser(HttpUser):
    wait_time = between(1, 3)

    def on_start(self):
        """每个虚拟用户启动时注册并登录，拿到鉴权 token。"""
        self.username = f"locust_{random.randint(10 ** 6, 10 ** 7)}"
        self.email = f"{self.username}@example.com"
        self.client.post("/api/users", json={
            "user": {"username": self.username, "email": self.email, "password": "password123"}
        })
        login = self.client.post("/api/users/login", json={
            "user": {"email": self.email, "password": "password123"}
        })
        self.token = login.json()["user"]["token"] if login.status_code == 200 else None

    @task(5)
    def browse_articles(self):
        self.client.get("/api/articles", params={"limit": 20})

    @task(3)
    def browse_tags(self):
        self.client.get("/api/tags")

    @task(1)
    def create_article(self):
        if not self.token:
            return
        title = f"locust article {random.randint(10 ** 6, 10 ** 7)}"
        self.client.post("/api/articles", json={
            "article": {
                "title": title,
                "description": "perf test",
                "body": "generated by locust",
                "tagList": ["locust"],
            }
        }, headers={"Authorization": f"Token {self.token}"})
